### ISSUE TITLE
Share buttons atop of each gif aren't consistent in position or placement

### ISSUE THREAD

**Issue by liyasthomas** [liyasthomas/helloish#1]
It overlays to the side of the page.

**Comment by twilderan** [comment]
Did i reproduce bug correctly? If yes, assign me for this)

![image](https://user-images.githubusercontent.com/29509266/65959204-0dba1800-e45a-11e9-94bd-5bbf6177e2ba.png)

**Comment by liyasthomas** [comment]
On small screens share buttons are not aligning correctly.
Currently these share buttons are absolutely positioned relative to hover image. May be you could simple use a CSS only tooltip kinda approach!

![Screen Shot 2019-10-01 at 5 19 14 PM](https://user-images.githubusercontent.com/10395817/65959474-b757d400-e46f-11e9-84b0-b122ad05c701.png)

**Comment by liyasthomas** [comment]
@twilderan thought I should ping you to know the status of this issue..

**Comment by twilderan** [comment]
oh, yeah, sorry, i forgot to respond on this ticket. i tested it on my local machine, i didn't get behavior from your screenshot, only this one: https://github.com/liyasthomas/helloish/issues/1#issuecomment-536999191

**Comment by liyasthomas** [comment]
https://github.com/liyasthomas/helloish/issues/1#issuecomment-537000276
On hover, share buttons going out of the hovered image. This is the issue. Issue persists on mobile devices as well as on large displays (zoom out to reproduce).
